apiVersion: v1
kind: Service
metadata:
  name: expedientedigital-web
  namespace: default
  labels:
    app: expedientedigitalweb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: expedientedigital-web
